### ISSUE TITLE
Can't Create Product

### ISSUE THREAD

**Issue by djeraseit** [tophatter/merchant-api-php#2]
`TophatterMerchantApi::setAccessToken('XXX');
$product = array(
    'identifier' => '6631A',
    'category' => 'Electronics|Hardware (Computers/Tablets/Phones)|Mobile',
    'title' => 'Apple iPhone 6S',
    'description' => 'This is the description.',
    'condition' => 'Refurbished - Manufacturer',
    'variations' => array(
      '6631A-WHITE' => array('identifier' => '6631A-WHITE', 'quantity' => 1),
      '6631A-BLACK' => array('identifier' => '6631A-BLACK', 'quantity' => 2)
    ),
    'starting_bid' => 1,
    'buy_now_price' => 150.0,
    'cost_basis' => 75.0,
    'shipping_price' => 5.0,
    'shipping_origin' => 'United States',
    'weight' => 6,
    'days_to_fulfill' => 3,
    'days_to_deliver' => 5,
    'primary_image' => 'https://d38eepresuu519.cloudfront.net/b2aa7d2708324f756ffee551ba43a74f/original.jpg',
    'extra_images' => 'https://d38eepresuu519.cloudfront.net/e615c55184c06f391dbd768f855904e6/original.jpg|https://d38eepresuu519.cloudfront.net/7cd125f0fa42c965675eabaf3309aa6d/original.jpg'
);
print_r(ProductApi::create($product));
`

**PHP Notice:  Undefined index: file** in /var/www/html/tnt/public_html/includes/tophatter/merchant-api-php/TophatterMerchant/TophatterMerchantApi.php on line 33
**PHP Notice:**  Undefined index: data in /var/www/html/tnt/public_html/includes/tophatter/merchant-api-php/TophatterMerchant/TophatterMerchantApi.php on line 33
**PHP Fatal error:  Uncaught Error:** Class 'TophatterMerchant\Exception\BadRequestException' not found in /var/www/html/tnt/public_html/includes/tophatter/merchant-api-php/TophatterMerchant/TophatterMerchantApi.php:62
Stack trace:
#0 /var/www/html/tnt/public_html/includes/tophatter/merchant-api-php/TophatterMerchant/ProductApi.php(47): TophatterMerchant\TophatterMerchantApi::getResponse('POST', 'products', Array)
#1 /var/www/html/tnt/public_html/includes/tophatter/merchant-api-php/test-product.php(44): TophatterMerchant\ProductApi::create(Array)
#2 {main}
  thrown in /var/www/html/tnt/public_html/includes/tophatter/merchant-api-php/TophatterMerchant/TophatterMerchantApi.php on line 62

**Comment by djeraseit** [comment]
It works adding 'color' to variations array. Php example should be updated.
